-- ProjNav VHDL simulation template: DatosLCD_tb_vhd.udo
-- You may edit this file after the line that starts with
-- '-- START' to customize your simulation
-- START user-defined simulation commands
